# Generated by Django 5.2.10 on 2026-01-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseversion',
            name='content_file',
        ),
        migrations.AddField(
            model_name='courseversion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='training_pdfs/'),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='training_videos/'),
        ),
    ]
