# Generated by Django 5.2.10 on 2026-01-09 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_videoprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoprogress',
            name='course_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='video_progress', to='courses.courseversion'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
