# Generated by Django 5.2.10 on 2026-01-13 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_videoprogress_course_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(default=True)),
                ('certificate_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='courses.assignment')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
