# Generated by Django 5.2.10 on 2026-01-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignmentcycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentcycle',
            options={'ordering': ['-completed_at'], 'permissions': [('can_audit_certs', 'Can search and download certificates for all users')]},
        ),
    ]
