# Generated by Django 5.2.10 on 2026-01-13 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quiz_quizquestion_quizchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='course_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz', to='courses.courseversion'),
        ),
    ]
