# Generated by Django 5.2.10 on 2026-01-16 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_quiz_course_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcycle',
            name='reminder_30_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentcycle',
            name='reminder_7_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentcycle',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentcycle',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentcycle',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assign_to_all_users', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('ANNUAL', 'Annual'), ('SEMIANNUAL', 'Semiannual'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly')], default='ANNUAL', max_length=20)),
                ('cycle_days', models.PositiveIntegerField(default=365)),
                ('remind_days_before', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseversion')),
            ],
        ),
    ]
