# Generated by Django 5.2.10 on 2026-01-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_assignmentcycle_reminder_30_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseversion',
            name='pdf_cache_bust',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='courseversion',
            name='video_cache_bust',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
