# Generated by Django 5.2.10 on 2026-01-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courseversion_pdf_cache_bust_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='annual_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='required_for_company',
            field=models.BooleanField(default=False),
        ),
    ]
